### ISSUE TITLE
Questions about the dataset preparation: the necessity of .zip format?

### ISSUE THREAD

**Issue by EndlessSora** [NVlabs/stylegan2-ada-pytorch#22]
@nurpax Hi, I have a question about the dataset preparation:

In [Preparing datasets](https://github.com/NVlabs/stylegan2-ada-pytorch#preparing-datasets) section, you mentioned that: "Alternatively, the folder can also be used directly as a dataset... but doing so may lead to suboptimal performance."

I'm a bit confused why we have to convert a folder dataset into the **.zip** format? Maybe because the original folder may not contain the uncompressed PNG files? Or any other considerations for the dataset format?

Thanks in advance!

**Comment by nurpax** [comment]
Hi @EndlessSora,

We prefer zip so that we can move datasets around computers and clusters easily.  But if you don't need to have your dataset in a single file archive, using images in file system folders should be just fine.

Under some network filesystem conditions, a zip archive can be more performant than many files on a filesystem.  

I recommend using the dataset_tool.py to convert your dataset (from image folders) to another folder structure.  This will convert PNGs (or other source image formats) into _uncompressed_ PNG that are fast to decode in the training code.  The dataset_tool.py also performs several data consistency checks that are probably easier to debug during dataset construction rather than at looking at asserts while training.

W.r.t., you shouldn't believe what a random guy on the internet tells you about performance. :smile:  For best results, try it out and benchmark yourself.  The key thing is GPU utilization -- as long as it stays at 95% or above, dataset ingest is performing just fine.

**Comment by EndlessSora** [comment]
Thanks a lot for your detailed clarification! It is very helpful. :)
